In [1]:
import numpy as np
import torch

## Auto Broadcasting

In [2]:
x = torch.rand(5, 3)
x
y = torch.rand(1, 3)
y
print(torch.add(x, y))

tensor([[1.0057, 1.8410, 1.0808],
        [0.7177, 1.6645, 0.9603],
        [0.6580, 1.0878, 0.1275],
        [0.9458, 1.5151, 0.8845],
        [1.1356, 1.5165, 0.5607]])


##  Resizing 

In [3]:
print(x.view(15))
print("hello", x.view(3, 5))

tensor([0.4199, 0.9134, 0.9644, 0.1319, 0.7368, 0.8439, 0.0723, 0.1602, 0.0111,
        0.3601, 0.5875, 0.7681, 0.5498, 0.5889, 0.4443])
hello tensor([[0.4199, 0.9134, 0.9644, 0.1319, 0.7368],
        [0.8439, 0.0723, 0.1602, 0.0111, 0.3601],
        [0.5875, 0.7681, 0.5498, 0.5889, 0.4443]])


##     Numpy Bridge

In [4]:
a = np.ones(4)
b = torch.from_numpy(a)
print(a, b, sep='\n')
"""
    Even though a is np array and b is torch tensor
    they are affected by the changes done to one of them
"""
np.add(a, 1, out=a)
print(a, b, sep='\n')

[1. 1. 1. 1.]
tensor([1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


### CUDA tensors
Tensors directly on GPU
Can be created and operated on GPU directly

In [5]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(b, device=device)
    b = b.to(device)
    z = b + y
    print(z)

tensor([3., 3., 3., 3.], device='cuda:0', dtype=torch.float64)


## Autograd

<p> The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.</p>
<h3><b>How to use it </b></h3>
<p><b>torch.Tensor</b> is the central class of the package. If you set its attribute <b><u>.requires_grad</u></b> as True, it starts to track all operations on it. When you finish your computation you can call <u><b>.backward()</b></u> and have all the gradients computed automatically. The gradient for this tensor will be accumulated into <u><b>.grad</b></u> attribute.</p>


In [6]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
out.backward()

In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
